default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qetl_development
  primary: &primary_development
    <<: *default
    database: qetl_development

test:
  <<: *default
  database: qetl_test

production:
  primary: &primary_production
    <<: *default
    database: qetl_production
    username: qetl
    password: <%= ENV["qetl_DATABASE_PASSWORD"] %>